### ISSUE TITLE
prompt compressed because of long path isn't updated when the terminal is resized

### ISSUE THREAD

**Issue by ghost** [nojhan/liquidprompt#550] opened 2018-06-04 02:28 UTC
Shell: zsh
Operating system: arch linux
Liquid Prompt version : eda83ef

Steps to reproduce:
1. Enable path compression
2. Open a fullscreen terminal
3. go to a deep directory
4. resize the terminal so that the prompt takes two lines
5. now the prompt will always take two lines on this terminal window.

Expected behaviour:

The new prompt length should be recomputed whenever the prompt is displayed.

**Comment by Rycieos** [comment] 2018-06-04 13:05
I can only somewhat reproduce; the path doesn't shorten immediately when downsizing the terminal, only once I change directories.

This is because of this check:
https://github.com/nojhan/liquidprompt/blob/eda83efe4e0044f880370ed5e92aa7e3fdbef971/liquidprompt#L1752-L1753
https://github.com/nojhan/liquidprompt/blob/eda83efe4e0044f880370ed5e92aa7e3fdbef971/liquidprompt#L1773

which will only run the path shortening when the directory is changed.

If I:
1. Open a fullscreen terminal.
2. `cd` into a long path.
3. Resize the terminal small.
I still have the full path (wrapping off screen).
4. `cd` into a different directory.
Path is now shortened in prompt.
5. Full screen terminal again.
6. `cd` into a different directory.
Path is now full again.

This is an unfortunate consequence of a needed check to prevent extra work if we aren't changing directories.

**Comment by gsaga** [comment] 2018-06-04 14:33
I followed these steps:

    Open a fullscreen terminal.
    cd into a long path.
    Resize the terminal small.
    I still have the full path (wrapping off screen).

That's what I see.

    cd into a different directory.
    Path is now shortened in prompt.

This is where I'm having some trouble. Even though the prompt is shortened, the part after the path still wraps over to the next line. Looks like some issue with `_lp_shorten_path`. Here's the `liquid.theme` file I use:
 

Full screen terminal again.
cd into a different directory.
Path is now full again.

**Comment by Rycieos** [comment] 2018-06-04 14:40
What is your `LP_PATH_KEEP` set at?
https://github.com/nojhan/liquidprompt/blob/eda83efe4e0044f880370ed5e92aa7e3fdbef971/liquidpromptrc-dist#L38-L41

It isn't designed to completely prevent wrapping: at the very least it will show the current directory name, and at least `LP_PATH_KEEP` number of directories from the root.

**Comment by gsaga** [comment] 2018-06-04 15:48
What is your LP_PATH_KEEP set at?

I've set it to be 3.

    It isn't designed to completely prevent wrapping: at the very least it will show the current directory name, and at least LP_PATH_KEEP number of directories from the root.

right, guess giving the path it's own line and setting the `LP_PATH_LENGTH` to 100 would be good enough.

**Comment by Rycieos** [comment] 2018-06-04 17:20
I'm pretty sure (if I understand this comment correctly:
https://github.com/nojhan/liquidprompt/blob/eda83efe4e0044f880370ed5e92aa7e3fdbef971/liquidprompt#L704-L705
) that `LP_PATH_KEEP` has a higher precedence than `LP_PATH_LENGTH`, meaning that if you set
```
LP_PATH_KEEP=128
LP_PATH_LENGTH=5
```
You will always see the full path.

**Comment by Rycieos** [comment] 2021-02-22 15:00
Closing this because
* The reporter's account was deleted
* The path shortening feature was rewritten as part of v2.0.0

If anyone can reproduce this with v2.0+, please open a new bug report.

**Closed by Rycieos** 2021-02-22 15:00 UTC
