### ISSUE TITLE
Battery wrong when two batteries in a Thinkpad

### ISSUE THREAD

**Issue by seraphyn** [nojhan/liquidprompt#493] opened 2016-11-30 12:20 UTC
Shell: bash
Operating system:  Debian jessie
Liquid Prompt version (tag, commit): 5ee3c53cbbc95b5288fe5baf5a3c5b21d2a7212d

liquidprompt shows only the first battery and not the second one, too.

13:15:27 ⌁23% [cmg:~/workspace/liquidprompt.git] master 141 ± acpi
Battery 0: Discharging, 23%, 00:17:43 remaining
Battery 1: Unknown, 99%

`tlp-stat -b |grep remaining_percent |awk '{ print $3 }'| tr '\n' ' '`

gives a
100 20

or a 
`acpi |awk '{ print $4 }'| tr '\n' ' '`
17%, 99%
could help here

**Comment by CoffeeFrame** [comment] 2017-02-22 03:43
I also have this problem and will look into it.

**Comment by dolmen** [comment] 2017-02-22 06:54
I think that the shell prompt is not the best place to show the *individual* status of each battery. It occupies to much space.

**Comment by seraphyn** [comment] 2017-02-24 07:45
@dolmen _individual_ status is the wrong term ;)
The correct status is the right term.
If my batteries will give me 3 hours more, or just 5 minutes is in a case of coding or administration of servers a big diffrent situation, isn't it?
And the possibility for those who like to have a shorter smaller  prompt could switch it of.

**Comment by Rycieos** [comment] 2020-07-05 13:22
Duplicate of #393.

**Closed** 2020-07-05 13:22 UTC
Labels: battery, duplicate
