### ISSUE TITLE
Prompt wraps on itself in Python virtualenv

### ISSUE THREAD

**Issue by vicchi** [nojhan/liquidprompt#547] opened 2018-05-17 15:32 UTC
Shell: GNU bash, version 4.4.19(1)-release (x86_64-apple-darwin17.3.0) (installed via Homebrew)
Operating system: macOS 10.13.4
Liquid Prompt version (tag, commit): 1.11 (according to Homebrew)

When running in a Python virtualenv there seems to be a clash between `liquidprompt` and `virtualenv`'s prompt settings, such that the resultant prompt wrap around on itself.

Which is clumsily worded, but the best way I can describe it. Hopefully the screen grab below will make more sense! You can see that the caret is on the far left of the prompt, preceded by `B]`, which looks like a messed up terminal escape sequence?

Is this a known issue or is there a `liquidprompt` option I need to set or a known `virtualenv` option I can set to resolve this?

<img width="682" alt="terminal" src="https://user-images.githubusercontent.com/442617/40187584-c3d9e292-59ef-11e8-843c-fb3aaec5bf07.png">

**Comment by vicchi** [comment] 2018-05-17 17:19
@Rycieos Running (Homebrew) Python 2.7.15 and `virtualenv` 16.0.0. Just cloned the `liquidprompt` repo so I'm running from the head of `master` rather than the Homebrew version (1.11) ... no change I'm afraid.

**Comment by dolmen** [comment] 2018-05-22 05:40
I'm the maintainer, but I don't use Python at all. Any diagnostic or fix will have to be provided by the community.

**Comment by Rycieos** [comment] 2020-07-07 16:38
I can reproduce this one! Only on Bash, pretty sure Zsh doesn't have this issue. Turns out it's not limited to virtualenvs (which makes sense, they aren't treated at all special in Liquidprompt), you are just noticing it then because it makes your PS1 longer. Or something like that. I'm still digging. No promises on being able to fix, but reproduction is a start.

Something super whack is happening I think. Often it works correctly:
```
θ17° [mark@jaguar:~/dev/zeroscale] [venv] master
 ± echo $COLUMNS
48
```
But if I make my terminal 1 character wider:
```
31m ± mark@jaguar:~/dev/zeroscale] [venv] master
```
I get this "31m" to show up while incorrectly wrapping. Which happens to be a terminal color escape code:
```
$ printf %s "$PS1" | od -c
0000000 316 270   \   [ 033   [   3   2   m   \   ]   1   7 302 260   \
0000020   [ 033   (   B 033   [   m   \   ]       [   \   u   \   [ 033
0000040   (   B 033   [   m   \   ]   \   [ 033   [   3   3   m   \   ]
0000060   @   \   [ 033   (   B 033   [   m   \   ]   \   [ 033   [   3
0000100   4   m   \   ]   \   h   \   [ 033   (   B 033   [   m   \   ]
0000120   \   [ 033   [   3   2   m   \   ]   :   \   [ 033   (   B 033
0000140   [   m   \   ]   \   [ 033   [   1   m   \   ]   ~   /   d   e
0000160   v   /   z   e   r   o   s   c   a   l   e   \   [ 033   (   B
0000200 033   [   m   \   ]   ]       [   \   [ 033   [   3   6   m   \
0000220   ]   v   e   n   v   \   [ 033   (   B 033   [   m   \   ]   ]
0000240       \   [ 033   [   3   2   m   \   ]   m   a   s   t   e   r
0000260   \   [ 033   [   3   1   m   \   ]   \   [ 033   (   B 033   [
0000300   m   \   ]       \   [ 033   [   1   m   \   ] 302 261   \   [
0000320 033   (   B 033   [   m   \   ]
...
m   a   s   t   e   r  \   [ 033   [   3   1   m   \   ]
```
And sometimes I can get it to print bad characters:
```
┬▒ 4┬░ [mark@jaguar:~/dev/zeroscale] [venv] master
```
And even more fun, that doesn't go away when I enlarge the terminal again. I have to `reset` to fix it.

It looks like either Bash or the terminal emulator is inserting a `\n` in the echoed string and breaking up the `\[\033[31m\]` sequence. Or more likely, the `\033[31m` sequence. Which is the ANSI sequence for "set forground red":
```
$ tput setaf 1 | od -c
0000000 033   [   3   1   m
0000005
```

Why is red there? In the prompt, the branch is green (`\   [ 033   [   3   2   m   \   ]   m   a   s   t   e   r`), then sets back to no color. But after master in PS1, it sets to red, then no color (`m   a   s   t   e   r   \   [ 033   [   3   1   m   \   ]   \   [ 033   (   B 033   [  m   \   ]`). Ok dug deeper, turns out it's a bad implementation in `_lp_git_branch_color()`, and it always puts red in the prompt for a git branch even if there is no special head status. I'll fix this in 2.0. And fixing it now didn't fix this problem.

Now the big question: why is BASH (or the terminal emulator, but probably not since it doesn't happen on Zsh) inserting a newline in the escape sequence? We wrap this with `\[ \]` for Bash so it knows they don't print, and the terminal emulator is grabbing them to color the output, so both should know not to do that. I double checked the output of my $PS1, and it does have the correct `\[ \]` escaping.

And even if that is really my problem, is it yours? Your screen shot shows something different, a break in the middle of a color. And we have other reported issues with similar wrapping problems where they prompt doesn't go all the way to the screen. Ugh. I'll keep digging.

**Comment by Rycieos** [comment] 2020-07-09 01:42
Hypothesis: Unicode characters are being incorrectly "sized" by Bash, and therefore make Bash split the PS1 in the wrong spot.

I set a PS1 that was pretty normal but had color near the end:
```
± prompt_OFF
$ red="$(tput setab 1)"
$ reset="$(tput sgr0)"
$ PS1="a super long prompt that doesn't work right \[$red\]redness\[$reset\] $ "
a super long prompt that doesn't work right redness $
a super long prompt that doesn't work right rednes
m $
```
Resizing the terminal here makes the prompt behave exactly correctly only some of the time....
Depending on how wide the window is, different characters show up after the \r, some which appear to be escape codes. So we are finding something similar to what I was seeing before.

If you play with the terminal width enough, you will get some very weird things to happen. Ideally (what happens in Zsh all the time and Bash with no colors), you can resize the terminal infinite times and the prompt will always look correct.

Hypothesis rejected: while Unicode characters might add to this (or be their own issue (or probably the cause of this issue??)), I can reproduce it with only ASCII characters in a PS1 with color.

New Hypothesis: Bash doesn't redraw the whole PS1 when terminal resizes. Can we force that?

I can produce some bugged output with no color at all:
```
$ PS1="a super long prompt that doesn't work right $ "
a super long prompt that doesn't work right $ 
a super long prompt that doesn't w
ork right $ 
a super long prompt th
at doesn't work right 
$ 
# Now expand the terminal a bit:
a super long prompt that does
n't work right $ ight  # Leftover chars
```
I even tested this with stock Bash settings (version 4.4.19(1)-release), and it still did it.
I also tested with Bash 3.2 (3.2.57(1)-release), and it was even worse, pasting up a line each time the window got larger.

This is looking a lot like a Bash bug. I'll keep digging though...

**Comment by Rycieos** [comment] 2020-07-09 21:09
Other guesses:
* Bash didn't get SIGWINCH: wrong, it always did, `echo $COLUMNS` always showed the right number.
* Some other program (like running Vim) caught the SIGWINCH and Bash had no idea: not the case, it happens on a brand new terminal window.

I can also reproduce the wrapping on the same line like so:
```
# set terminal size to 52 wide
$ PS1="θ a decently long prompt that wraps on itself \[$(tput setaf 6)\]blues\[$(tput sgr0)\] $ "
 $  decently long prompt that wraps on itself blues 
```
It doesn't happen if you replace the theta (θ) with an ASCII char:
```
$ PS1="0 a decently long prompt that wraps on itsel \[$(tput setaf 6)\]blues\[$(tput sgr0)\] $ "
0 a decently long prompt that wraps on itself blues 
$ 
```
or remove the color escape codes:
```
$ PS1="θ a decently long prompt that wraps on itself blues $ "
θ a decently long prompt that wraps on itself blues 
$ 
```

**Comment by Rycieos** [comment] 2020-07-16 13:30
I'm actually stumped here.

When I compiled 4.4.19 myself (and 4.4.23 and 5.0.17), I get this:

```
$ PS1="a super long prompt that doesn't work right $ "
<doesn't work right $ 
```
The prompt auto hides sections as you change the terminal size, and as you type on the line. I couldn't find documentation for this behavior. And this does not happen on the version of Bash that shipped with CentOS.

```
Compilation CFLAGS:  -DPROGRAM='bash' -DCONF_HOSTTYPE='x86_64' -DCONF_OSTYPE='linux-gnu' -DCONF_MACHTYPE='x86_64-redhat-linux-gnu' -DCONF_VENDOR='redhat' -DLOCALEDIR='/usr/share/locale' -DPACKAGE='bash' -DSHELL -DHAVE_CONFIG_H   -I.  -I. -I./include -I./lib  -D_GNU_SOURCE -DRECYCLES_PIDS -DDEFAULT_PATH_VALUE='/usr/local/bin:/usr/bin'  -DSYSLOG_HISTORY -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wno-parentheses -Wno-format-security
```

Anyway, this issue and related are actually starting to have an effect on my mental health, so I'm taking a break from them. These won't make 1.12. Help wanted to get to the bottom of this and find fixes!

**Comment by dreamcat4** [comment] 2021-12-06 17:24
Hello @Rycieos yes i am seeing the same bug here. When using liquiqprompt in Tilix terminal program. And also using some custom VTE hooks. (VTE is needed to remember the current directory when opening a new window or a new tab).

It started happening a while ago. Unfortunately I cannot give any clear point when. But I believe it might have been after upgrading from one version of ubuntu to a newer version during the last couple of years.

I do agree with your assessment is that the most likely reason is because the ansi escape color codes / control characters such as `\[31m` etc. Well they are non-printing characters. However it looks as if they are somehow getting counted towards the visible 'columns' width by mistake. For the word wrapping linebreak.

Can you please respond and let us know if you are also using tilix yourself? Or VTE feature in your login script? Or are you using some other different terminal environment?

BTW my `TERM*` env vars:

```sh
± env | grep -i term
COLORTERM=truecolor
GNUTERM=dumb
TERM=xterm-256color
```

again, not sure if any of that stuff actually matters or not. No idea

**Comment by dreamcat4** [comment] 2021-12-06 17:31
ah...
Maybe I have stumbled upon the answer just now. Over on the Arch Wiki:

https://wiki.archlinux.org/title/Bash/Prompt_customization#PROMPT_COMMAND

The not highlighted in Red color. Where it says:

> Warning: PROMPT_COMMAND generally should not be used to print characters directly to the prompt. Characters printed outside of PS1 are not counted by Bash, which will cause it to incorrectly place the cursor and clear characters. Either use PROMPT_COMMAND to set PS1 or look at embedding commands.

So maybe something is setting `PROMPT_COMMAND`. However I am not sure yet where this is happening. If it's in liquidprompt code. Or if it's elsewhere in my local config (for example the VTE customization, or other customization which was setup in my login script, etc.)

Will have to look into that a bit further.

**Comment by Rycieos** [comment] 2021-12-07 17:49
> > Warning: PROMPT_COMMAND generally should not be used to print characters directly to the prompt. Characters printed outside of PS1 are not counted by Bash, which will cause it to incorrectly place the cursor and clear characters. Either use PROMPT_COMMAND to set PS1 or look at embedding commands.
> 
> So maybe something is setting `PROMPT_COMMAND`. However I am not sure yet where this is happening. If it's in liquidprompt code. 

`liquidprompt` does set `PROMPT_COMMAND`:
https://github.com/nojhan/liquidprompt/blob/c5d630d5291dab83eb36cf760a541e093eb8a410/liquidprompt#L3128

But `__lp_set_prompt()` does not print anything. It sets `PS1` to a string, and lets Bash evaluate it.

> Or if it's elsewhere in my local config (for example the VTE customization, or other customization which was setup in my login script, etc.)

If you do set `PROMPT_COMMAND` elsewhere, that could be causing it too. I would test this with a totally clean environment to see if you can get it to break (`env -i bash --norc --noprofile`).

But I'm 90% sure this is a bug in Bash. I can make this break on three different terminal emulators (iTerm2, Windows Terminal, MinTTY) with Bash 3.2. Sometimes Bash 4.4 also breaks. Nothing is consistent, but since I can make it happen without Liquidprompt being loaded, I doubt it is a problem with Liquidprompt.

If you can get me some specific reproduction steps, I will try them. I do have a Linux Desktop, so I could try Tilix if your repro steps use that.

**Comment by gwd666** [comment] 2023-01-19 19:05
I have also started witnessing this with the `powerprompt` prompt in WSL2 Ubuntu 20.04 `bash` even, when environments are not activated. the `default` and `lp_theme alternate_vcs` prompts work fine

**Comment by Rycieos** [comment] 2023-01-19 19:13
> I have also started witnessing this with the `powerprompt` prompt in WSL2 Ubuntu 20.04 `bash`

I'm assuming (from your linked issue) you mean the `powerline_full` theme.

Could you test with my above suggested steps to see if a clean environment still has the issue?
```bash
env -i bash --norc --noprofile
. liquidprompt  # or whereever you have it
. liquidprompt/themes/powerline/powerline.theme
lp_theme powerline_full
```

And if so, please include your reproduction steps, as well as what issue you see with the prompt.

**Comment by gwd666** [comment] 2023-01-19 19:25
@Rycieos hi - it's both the `powerline_full` and the `powerline` theme 
interesting additional fact it will wrap once and then after it has filled the line it will move to the next line

**Comment by gwd666** [comment] 2023-01-19 19:33
`lp_theme powerline_full` throws a command not found error, where does that reside?

**Comment by gwd666** [comment] 2023-01-19 20:17
PS: I am on `commit 6f0dc9f7dda99fe98c6dce26be5e461692782c6d (HEAD -> stable, tag: v2.1.2, origin/stable)`

**Comment by Rycieos** [comment] 2023-01-19 21:53
Ah, I forgot you need to set `TERM` or Liquid Prompt thinks you are in a dumb terminal:
```bash
$ env -i $(which bash) --norc --noprofile
bash-5.2$ export TERM=xterm-256color
bash-5.2$ . ~/dev/liquidprompt/liquidprompt
[mark:~/Users/mark] $ . ~/dev/liquidprompt/themes/powerline/powerline.theme
[mark:~/Users/mark] $ lp_theme powerline_full
aaaaaaaaa^C Users  mark  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
 mark  ~  Users  mark  130 
```

It seems I can reproduce this, and I'm using iTerm2 v3.4.18 on MacOS 13.0.1, GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.1.0). What is SUPER WEIRD is that it only breaks when I'm in the shell with no environment, like above. When I `lp_theme` from my normal environment, the above issue does not happen. Well, it actually isn't that weird, because `LANG` was not set. As soon as I set `export LANG=en_US.UTF-8`, the issue went away. You should try that.

Trying with my earlier examples, I can only make it break on Bash-3.2. Bash-5.2 seems quite resistant to the simple examples. Setting `LANG` on Bash-3.2 did not help with the earlier examples. It seems no matter what resizing the terminal window would make weird things happen. So maybe also try upgrading Bash?

So for completeness, everyone please test with this complete set of commands:
```bash
env -i $(which bash) --norc --noprofile
export TERM=xterm-256color
export LANG=en_US.UTF-8  # or your language of choice, but must be UTF-8 mode.
. ~/liquidprompt/liquidprompt  # or whereever you installed.
. ~/liquidprompt/themes/powerline/powerline.theme
lp_theme powerline_full
echo $COLUMNS
# Try to get it to break: wrap, resize the terminal, etc.
```

**Comment by gwd666** [comment] 2023-01-20 11:34
let me check with `LANG=en_US.UTF-8` though my "usual" setting there would be `C.UTF-8` so my guess would be hat it should not make any diff? 
running check now 
and yes, switching `C.UTF-8` to `en_US.UTF-8` fixed it for me (as well)

**Comment by Rycieos** [comment] 2023-01-20 17:16
Thanks for testing @gwd666, glad we could resolve this.

Since that's two confirmed fixes (myself included), I'm closing this issue. If anyone (especially @vicchi or @dreamcat4) still has this issue after setting a UTF-8 encoding, please comment or open an new issue.

**Closed by Rycieos** 2023-01-20 17:16 UTC
Labels: bash, help wanted
