### ISSUE TITLE
Bash 4.4.11 Command time and return status

### ISSUE THREAD

**Issue by izissise** [nojhan/liquidprompt#516] opened 2017-04-19 14:33 UTC
Shell: bash 4.4.11
Operating system: Debian
Liquid Prompt version (tag, commit): 93df0169499c4ca8563add267e95dcd343d95f12

Hello,
When using liquid prompt with bash 4.4.11, the time taken by a command doesn't work properly, it is always displayed and it shows the time since the shell was launched.
Also the return code of command doesn't shows even for non-zero return status.

**Comment by nolanl** [comment] 2017-10-23 17:57
I see the same 2 problems, Also Debian, bash version 4.4.12.

**Comment by vabada** [comment] 2017-11-03 16:13
I have the same problem! Any way we can help to fix it?

**Comment by Rycieos** [comment] 2017-11-03 17:58
We will probably need some example output of it not working as intended. Running a few commands with the wrong output would help. As it is right now we don't have enough info to start figuring out what is wrong.

Relevant code sections:
https://github.com/nojhan/liquidprompt/blob/9c80396021a8106bfaeade9a1ea51b85152e951d/liquidprompt#L1408-L1420

https://github.com/nojhan/liquidprompt/blob/9c80396021a8106bfaeade9a1ea51b85152e951d/liquidprompt#L1437-L1459

@nolanl and @vabada, we could use your shell and shell version info, as well as confirming that your liquidprompt is up to date.

**Comment by nolanl** [comment] 2017-11-03 22:56
@Rycieos Thanks for taking a look.

```
[:~/bin/upstream/liquidprompt] master ± git pull
Current branch master is up to date.

[:~] $ echo $BASH_VERSION
4.4.12(1)-release

[:~] $ false
[:~] $ true
[:~] $ 

[:~] $ grep RUNTIME .config/liquidpromptrc 
# Show runtime of the previous command if over LP_RUNTIME_THRESHOLD
LP_ENABLE_RUNTIME=1
LP_RUNTIME_THRESHOLD=10
[:~] $ sleep 11
[:~] 40s $ 
[:~] 51s $ 
[:~] 51s $ 
[:~] 52s $ 
[:~] 52s $ 
[:~] 52s $ true
[:~] 55s $ false
[:~] 56s $ 
```

**Comment by vabada** [comment] 2017-11-04 09:27
Hi!
So my shell is: `GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)`
And some code output:
~~~
[vabada:~] $ cd .liquidprompt/
[vabada:~/.liquidprompt] master 5s ± git pull
Already up-to-date.
[vabada:~/.liquidprompt] master 7s ± 
[vabada:~/.liquidprompt] master 8s ± 
[vabada:~/.liquidprompt] master 9s ± 
[vabada:~/.liquidprompt] master 10s ± git remote -v
origin	https://github.com/nojhan/liquidprompt.git (fetch)
origin	https://github.com/nojhan/liquidprompt.git (push)
[vabada:~/.liquidprompt] master 23s ± 
[vabada:~/.liquidprompt] master 30s ± 
~~~

**Comment by nolanl** [comment] 2017-11-04 17:47
Actually, I slightly mischaracterized the issue with LP_RUNTIME_THRESHOLD.  It doesn't require a slow command at all.  It displays the time since shell process creation in any shell once LP_RUNTIME_THRESHOLD seconds have passed, even if the shell was not executing any commands.

If I open a new terminal, do nothing, wait LP_RUNTIME_THRESHOLD seconds, and then hit enter, it shows the time in the prompt.  All subsequent prompts continue to have the time.

**Comment by Rycieos** [comment] 2017-11-06 19:06
It has to be the section here not running and resetting the time since last command.
https://github.com/nojhan/liquidprompt/blob/9c80396021a8106bfaeade9a1ea51b85152e951d/liquidprompt#L1444-L1445

I have no idea why it is doing that though. I don't really even understand how line 1445 is working setting two variables on the same line. Maybe @dolmen will have some idea.

Could you guys share the output of `env`, just in case there is anything that could be causing this.

**Comment by Rycieos** [comment] 2017-11-06 19:09
I just tried this in my shell:
```
$ foo=-1 bar=4
$ echo $foo
-1
$ echo $bar
4
```

So apparently that is valid in bash and ksh.

**Comment by nolanl** [comment] 2017-11-06 19:33
```
[:~] $ env
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LANG=en_US.UTF-8
GDM_LANG=en_US.utf8
DISPLAY=:0
XDG_VTNR=7
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XDG_SESSION_ID=181
XDG_GREETER_DATA_DIR=/var/lib/lightdm/data/nolan
USER=nolan
DESKTOP_SESSION=lightdm-xsession
PWD=/home/nolan
HOME=/home/nolan
SSH_AGENT_PID=15127
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/home/nolan/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
AUTOJUMP_ERROR_PATH=/home/nolan/.local/share/autojump/errors.log
XDG_SESSION_DESKTOP=lightdm-xsession
AUTOJUMP_SOURCED=1
TERM=xterm
SHELL=/bin/bash
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
PYTHONSTARTUP=/home/nolan/.pythonrc
XDG_SEAT=seat0
SHLVL=2
PROMPT_COMMAND=history -a; _lp_set_prompt
GDMSESSION=lightdm-xsession
LOGNAME=nolan
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/home/nolan/.Xauthority
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
PATH=/home/nolan/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin
GCC_COLORS=error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01
_=/usr/bin/env
```

**Comment by nolanl** [comment] 2017-11-06 21:12
Ah, I think I've found a clue.  From my .bashrc:
    . ~/bin/upstream/liquidprompt/liquidprompt
    export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

which results in PROMPT_COMMAND being:
    [:~] $ echo $PROMPT_COMMAND 
    history -a; _lp_set_prompt

Obviously, the return code from "history -a" is clobbering the return code of the previous command.

Reversing the order of the "history -a" and the "$PROMPT_COMMAND" fixes the return code printing, but not the always displaying the time issue.  This part I don't understand.

**Comment by nolanl** [comment] 2017-11-06 21:13
Forgot to mention, commenting out the setting of PROMPT_COMMAND entirely fixes both the return code printing and the always printing the time issue.

**Comment by Rycieos** [comment] 2017-11-06 21:32
Ah, in that case, this seems like a duplicate of #352 and #450.

@izissise and @vabada, can you check if you are setting `$PROMPT_COMMAND` anywhere?

[This comment](https://github.com/nojhan/liquidprompt/issues/352#issuecomment-87701786) describes the correct way to customize `$PROMPT_COMMAND`.

**Comment by nolanl** [comment] 2017-11-06 21:45
Yep, swapping the order fixed it.  Thanks for the pointer to the fix!

**Comment by vabada** [comment] 2017-11-06 22:25
Fixed! Amazing, thank you!

**Comment by izissise** [comment] 2017-11-07 09:45
Reversing fixes the return code but not the time issue for me.
My PROMPT_COMMAND:
```
[[ $- = *i* ]] && PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}"'if [ "$(id -u)" -ne 0 ]; then echo "$(date "+%Y-%m-%d.%H:%M:%S") $(pwd) $(history 1)" >> ~/.bash/bash-history-$(date "+%Y-%m-%d").log; fi;'
```
Relevent env vars:
```
LC_ALL=en_US.UTF-8
HOSTTYPE=x86_64-linux
COLORTERM=truecolor
USER=izissise
PWD=/home/izissise
HOME=/home/izissise
TERM=xterm-256color
SHELL=/bin/bash
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
PATH=/home/izissise/.cargo/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
_=/usr/bin/env
```

**Comment by izissise** [comment] 2017-11-07 16:14
The purpose it to do as described in this blog post:
https://spin.atomicobject.com/2016/05/28/log-bash-history/
But removing the prompt_command assignation does fix the issue.

**Comment by izissise** [comment] 2017-11-07 19:14
I wasn't setting PROMPT_COMMAND before liquidprompt, I moved it and all is working correctly!
Thanks you ;)

**Comment by Rycieos** [comment] 2017-11-07 19:19
Don't forget to close the issue.

**Comment by nolanl** [comment] 2017-11-07 21:06
It might be useful to print an error message if PROMPT_COMMAND is not "_lp_set_prompt".  Reduce noise on the bug tracker and all.

**Closed** 2017-11-07 21:07 UTC

**Comment by dolmen** [comment] 2017-11-08 16:24
@nolanl There are so many ways to shoot yourself in the foot. Liquid Prompt can not protect you from all. Especially because checking the value of `$PROMPT_COMMAND` every time the prompt is displayed has a cost (I know, not much compared to the other massive things that LP does, but anyway).
