### ISSUE TITLE
IP address

### ISSUE THREAD

**Issue by nojhan** [nojhan/liquidprompt#723] opened 2022-08-16 20:19 UTC
Display the IP address.

### Description

Add the local IP address next to the hostname.
Optionally, if the IP is one of a loopback one (localhost, 127.0.0.1, etc.), keep it hidden.
Use different colors if the IP is a public one (yellow?), a private network (green?) or a loopback (blue?) (cf. https://en.wikipedia.org/wiki/Reserved_IP_addresses).

I suggest to disable this feature as a default.

This probably would need the user to indicate the network interface of choice.

**Comment by Rycieos** [comment] 2022-08-21 15:41
> This probably would need the user to indicate the network interface of choice.

I'm not a fan of this. I shot down a similar method for battery detection, because I want things to work without extra configuration needed. Being disabled by default would help that, but I still do not like it.

The bigger issue is IP families. With both IPv4 and IPv6, most interfaces will have at least 3 addresses. My interfaces all have 4:
```
    inet 192.168.2.3/24 brd 192.168.2.255 scope global dynamic noprefixroute           # private
    inet6 fd6a:xxxx:xxxx:2:xxxx:xxxx:xxxx:9778/64 scope global dynamic noprefixroute   # private
    inet6 2601:xxx:xxxx:xxxx:xxx:xxxx:xxxx:afa6/64 scope global dynamic noprefixroute  # public
    inet6 fe80::xxxx:xxxx:xxxx:c39f/64 scope link noprefixroute                        # link-local
```
How do you pick which one to show? The most left on the spectrum of `public - private - link-local - loopback`? Show all of them?

The problem is how long IPv6 addresses are. You really should not put them in a prompt. But only supporting IPv4 address seems too backwards to me. I do not use IPv4 at home at all; I only have it enabled to support sites still stuck on IPv4 only. I would consider this feature flawed if it only supported IPv4.

I guess my question is why this is needed at all? IP addresses are for computers; hostnames and DNS records are for human consumption. I could see an argument that if a hostname is not set, show the IP address instead. But I think most OSes already do that.

**Comment by nojhan** [comment] 2023-08-05 04:56
I also realized most of my laptops are also connected on bothe wifi and ethernet, and I wouldn't know wich IP to display.

I think you're probably right that this is not worth the effort.

**Comment by Rycieos** [comment] 2023-08-05 20:31
Closing since I don't see a reason to see IP addresses when we already have hostnames.

**Closed by Rycieos** 2023-08-05 20:31 UTC
Labels: enhancement, rejected feature
