### ISSUE TITLE
add support for Termux xterm-256color terminal

### ISSUE THREAD

**Issue by go2null** [nojhan/liquidprompt#586] opened 2019-10-10 14:37 UTC
Shell: bash v5.0.11
Operating system: Termux (Android, Samsung Tab S2)
Liquid Prompt version (tag, commit): master (from: https://github.com/pearl-hub/liquidprompt)

Getting the following error message (repeated) when starting Termux
```
liquidprompt: terminal xterm-256color not supported
liquidprompt: terminal xterm-256color not supported
```

**Comment by Rycieos** [comment] 2020-06-11 15:55
This is usually caused by the terminal not supporting text coloring with the `tput` command. Liquidprompt tests `tput` to see which version you have and if it can figure out how to use it to color the terminal. If it can't find a way to use `tput`, it prints that error message.

Sometimes the `$TERM` variable can be set incorrectly, and `tput` won't know how to interact with your terminal. You can test this pretty easily with `tput setaf 1`. It's also possible that Termux doesn't ship with `tput`, in which case you would need to install it to use Liquidprompt.

What happens when you run these commands?
```
tput setaf 1
tput -T xterm setaf 1
```

**Comment by Rycieos** [comment] 2022-05-20 20:17
Closing due to no update from the original reporter, and it is most likely a terminal issue.

**Closed** 2022-05-20 20:17 UTC
Labels: invalid, TERM, needs information
