### ISSUE TITLE
ansi color codes mess up line wrapping - (in gnome terminal and tilix)

### ISSUE THREAD

**Issue by dreamcat4** [nojhan/liquidprompt#706] opened 2022-05-11 12:41 UTC
In some terminal programs (but not others). The non-printed ansi color colors escape codes somehow are getting counted towards the cursor position / line length. Such that the tty wrapping onto the next line occurs 'too early' before the real full width of the terminal is reached by the current cursor position. (i.e. the true last column, at the very right hand edge of the window, whatever the size of the window has made the column width)

Terminal Programs i tested here on my setup that are affected by this issue:

* gnome terminal
* tilix

Terminal Programs which do not seem to be affected:

* alacritty
* kitty

Note:
It is worth pointing out here that while the last of these programs (kitty) supports tabs, it does not seem to be working for the VTE feature, to pass the CWD into any spawned tab (remember the current folder, and open in that same folder).

We were in fact discussing on gnome's VTE issue tracker (in gnome gitlab) that the broken nature of the VTE feature in bash, due to a long time missing feature of bash to support arrays for the prompt variable. However in recent (newest) versions of bash this missing feature has now been added. 

So there is actually now a NEW method of taking advantage of this improved situation, such that it gives a much better interoperability between VTE, and also other custom 3rd party prompts such as liquidprompt here. So that you can have them each (BOTH) happily loaded into the promp allongside each other as they can each be sourced into their own individual elements of the array.

The previous method was rather too hacky for everybody's liking, because you had to basically re-insert the vte back in all in the same prompt variable. And in fact I had to make a special re-entry hook function. That was super over complicated mess. Heaven knows looking back at my code how it worked, but basically it had to set a seperate auxiliarry variable to track whethere it had already been loaded before or not, so that the re-entrant vte _osc* function then was overriden, and with the extra check to stop an infilnite loop of including itself over and over...

So this new prompt array mode in bash is supposed to now solve all that and avoid such hacks entirely. However the last time i looked at your liquidprompt code (few months ago now). This new method has not yet been added. Because it needs adding into liquiq prompt, some extra handling (to detect the bash version, if the new method is supported or not by the shell that the user has installed, if they are still on the older bash they cannot use this new feature).

So to support that you need to add some extra check or something around those couple of places where you are setting the prompt.

Sorry if that is thin on details and difficult to follow. Because I am just speaking from memory here. But there will be further references added to the issue later on, to give better specifics where to find more infos about this madness.

===

Shell name and version: `bash 5.1.4(1)-release`

Shell:

  `uname -a` = `Linux apex 5.15.36-xanmod1-tt #0~git20220427.beecca8 SMP Wed Apr 27 15:34:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

```sh
 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute

DE: Budgie 10.5.2 
WM: Mutter(Budgie)
```

Liquidprompt version:  `git rev-parse HEAD` = `24945b9b447976efa6e3ce6682a6d0a2b600c565`

### Steps to Reproduce

1. Open a color terminal `xterm-256color` in those application, and source the `~/.profile`, including the liquidprompt and the VTE function (from `/etc/vte/vte*` script)
2. Ensure that there is enough 'hidden characters' embedded into the prompt
3. Start typing, keep typing
4. Observe that the line wraps before the end of the line

### Expected Behavior

Non-printing characters that are embedded within the prompt all need to be detected and omitted from the tracking of the cursor's current column position.

This includes any ANSI color code escape sequences. And also any special call to the VTE shell function, which is needed for passing the current directory thru the VTE api --> when spawning a new tab

### Current Behavior

It does not work. Here is an example in GNOME Terminal (i took today)

```sh
[id:~] $ printf '%q\n' "$PS1"
locale
$'[id\\[\E(B\E[m\\]\\[\E[32m\\]:\\[\E(B\E[m\\]\\[\E(B\E[m\E[1m\\]~\\[\E(B\E[m\\]] \\[\E[1m\\]$\\[\E(B\E[m\\] \E]7;file://apex/home/id\E\\'
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
[id:~] $ echo mary had a little laecho mary had a little lamb here fleece was white as snow. everywhere
mary had a little lamb here fleece was white as snow. everywhere
s d:~] $ echo mary had a little lamb her fleece was white as snow. everywhere that mary went the lamb wa 
mary had a little lamb her fleece was white as snow. everywhere that mary went the lamb was

[id:~] $ env -i bash --norc --noprenv -i bash --norc --noprofile
bash-5.1$ 
bash-5.1$ . ~/.dev/liquidprompt/liquidprompt
liquidprompt: terminal 'dumb' does not support foreground colors
liquidprompt: terminal 'dumb' does not support background colors
[id:~/home/id] $ echo $TERM
dumb

[id:~/home/id] $ # ok, lets try again! (in bare shell)
[id:~/home/id] $ echo mary had a little lamb her fleece was white as snow. everywhere that mary went the lamb was sure to go!
mary had a little lamb her fleece was white as snow. everywhere that mary went the lamb was sure to go!
[id:~/home/id] $ # OK - this is working            
probably because there are no embedded ANSI color codes, since those are the very thing being mis-counted for the line wrapping.

But if it isn't the ANSI color codes, then maybe it's the embedded VTE function
[id:~/home/id] $ 
```

Same issue on Tilix:

See the last word `ever` --> only `e` was printed in the tty before it got wrapped onto the next line, where it overwrites the next line's prompt starting at the 1st column `[id:~] $` --> `ver:~] $`. (However then upon hitting return that itself was overwritten again by the echo command, so we didn't see that here).

```sh
[id:~] $ printf '%q\n' "$PS1"
locale
$'[id\\[\E(B\E[m\\]\\[\E[32m\\]:\\[\E(B\E[m\\]\\[\E(B\E[m\E[1m\\]~\\[\E(B\E[m\\]] \\[\E[1m\\]$\\[\E(B\E[m\\] \E]7;file://apex/home/id\E\\'
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
ver:~] $ echo mary had a little lamb her fleece was white as snow. e 
mary had a little lamb her fleece was white as snow. ever
[id:~] $ 
```

### Possible Solution

Well I have not check up your master branch code recently. Did you already improve this prompt setting code, to handle the new feature?

If not, then we really should think to update those couple of specific places in the liquidprompt code. So it can optionally use the new method. But it must first detect that the feature is supported by the parent shell. And only if the parent shell version is new enough, that actually supports the feature.

**Comment by dreamcat4** [comment] 2022-05-11 12:49
My last (most recent) activity, 7 months ago:

https://gitlab.gnome.org/GNOME/vte/-/issues/37#note_1280997

The 'magical solution' (that bash project finally caved and gave us what we needed):

https://gitlab.gnome.org/GNOME/vte/-/issues/37#note_1280976

So this is what liquidprompt perhaps can be improved to do this ^^. But what stopped me from trying it out here was I didn't know how to detect first, and do special case handling. Because you want to be sure it does not break the setting of the `PROMPT_COMMAND=` for legacy users, who are still using older versions of `bash`. Before this new array feature got added.

Needs a bit of further investigation / experimenting / testing.

**Comment by Rycieos** [comment] 2022-05-11 16:17
For the `PROMPT_COMMAND` bit, you already have #684 for that. I was looking at it again yesterday, and just pushed a commit.

But I don't see how that is related to the line wrapping issue. Unless they are related somehow, keep discussion on that contained to #684.

Anyway, I can actually reproduce this using your PS1. And with nothing else in common to you; MinTTY on Windows, Bash 4.4.20(1)-release, no VTE. It looks like there is a section of PS1 that is causing this:

>  ` \E]7;file://apex/home/id\E\\'`

This is not wrapped in Bash sequence escapes, so Bash thinks those characters are part of the prompt. That is why it wraps early. That string is not added by Liquidprompt. In fact, I had to look up `\E]7;` to see what it did:

https://iterm2.com/documentation-escape-codes.html
 
> The following synonym is available as a combination of RemoteHost and CurrentDir:
>
> `OSC 7 [Ps] ST`
>
> where `[Ps]` is a file URL with a hostname and a path, like `file://example.com/usr/bin`.

It all checks out. My guess is either the terminal or VTE is adding that? Either way, it's not a bug in Liquidprompt. When I remove the above string from PS1, things work correctly again.

I'm closing this as it's not an issue with Liquidprompt. Feel free to show me otherwise, or just keep the conversation going to try to diagnose where the issue is actually coming from.

**Closed** 2022-05-11 16:17 UTC
Labels: bug, invalid

**Comment by dreamcat4** [comment] 2022-05-11 19:27
thanks so much for looking into this my friend! ... cannot thank you enough. it's really made my day over here.

Now this is a very long comment, but it was to be comprehensive all the details of my activities. To be clearer - that nothing was left out to chance.

Lets begin!

OK so, you mention something here called the "`OSC 7`". This you have honed into here does indeed come from VTE. However as you are also (should be) aware by now it was necessary for my to make certain customizations or hacks on top of the stock VTE. At least for the specific version of the VTE script that get provided by my distro, which is ubuntu. (the distro maintainers themselves also can have extra patches or tweaks applied which isn't present on other distros).

However (for me) this is all a long time ago now. And all forgotten about. But I do very clearly remember that it actually all was working fine (those complex hacks) for a couple of years to begin with. Until midway I upgraded my whole ubuntu (which again, i cannot remember now those specifics), maybe when upgrading from 18.04 --> 20.04, or to 21.04, (whenever, the point is that multiple packages in the distro got updated, both bash packages and the VTE scripts). And so the cause of the breakage was not known. This bug then started happening to me for the 2nd half of this whole period. Where those special VTE customizations / hacks still worked. I can still use both liquidprompt and VTE working together. However now the bug of the line wrapping was occuring.

If you followed that short summary? Then the answer clearly! Must be: that I need to now remove all of my initial customizations, right? Absolutely! So today (in new hopes) OK I completely remove all of my previous customizations 100% this evening. (and also in my `~/.profile`). And returned the VTE script back to it's own stock ubuntu version. As follows:

* file: `/etc/profile.d/vte-2.91.sh`
* from: `libvte-2.91-common_0.62.3-1ubuntu1_amd64.deb`

and here is the full contents (un-edited, stock) of that file, as officially distributed in ubuntu releases:

```sh
$ cat /etc/profile.d/vte-2.91.sh 
# Copyright © 2012 Christian Persch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Not bash or zsh?
[ -n "${BASH_VERSION:-}" -o -n "${ZSH_VERSION:-}" ] || return 0

# Not an interactive shell?
[[ $- == *i* ]] || return 0

# Not running under vte?
[ "${VTE_VERSION:-0}" -ge 3405 ] || return 0

__vte_osc7 () {
  printf "\033]7;file://%s%s\033\\" "${HOSTNAME}" "$(/usr/libexec/vte-urlencode-cwd)"
}

__vte_prompt_command() {
  local pwd='~'
  [ "$PWD" != "$HOME" ] && pwd=${PWD/#$HOME\//\~\/}
  pwd="${pwd//[[:cntrl:]]}"
  printf "\033]0;%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${pwd}"
  __vte_osc7
}

case "$TERM" in
  xterm*|vte*)
    [ -n "${BASH_VERSION:-}" ] && PROMPT_COMMAND="__vte_prompt_command"
    [ -n "${ZSH_VERSION:-}"  ] && precmd_functions+=(__vte_osc7)
    ;;
esac

true
[id:~] $ 

```


OK... then the task now is that I need to cleanly source both liquidprompt, and also the VTE hook function when my `~/.profile`. When my interactive shell is loaded. But first I must be certain to double check all old customizations were completely gone. To be 100% clean.

Did a `ctrl+f` search the rest of my `~/.profile` for any other references to `PROMPT_COMMAND` and `PS1`. There are now 0 references.

... Then looked for elsewhere references to setting the prompt. The search was in all of `/etc/` as follows:

```sh
[id:/etc] $ sudo grep -R -i "prompt_command" /etc/ 2> /dev/null

/etc/profile.d/vte-2.91.sh:__vte_prompt_command() {
/etc/profile.d/vte-2.91.sh:    [ -n "${BASH_VERSION:-}" ] && PROMPT_COMMAND="__vte_prompt_command"
/etc/bash.bashrc:#    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
θ127° [id:/etc] 2 $ 
```

Yes! ...we can see those VTE shell functions here, (which is coming from official ubuntu packaging of `libvte`). And also the global `/etc/bashrc` of BASH package. Those are all stock versions from the distro.

Allright! So we a ready to begin now? OK going back to edit my `~/.profile`,

### Test 1

Added back these 2 lines only:

```sh
. ~/.dev/liquidprompt/liquidprompt
. /etc/profile.d/vte.sh
```

Where the `vte.sh` above ^^ is a symlink to `/etc/profile.d/vte-2.91.sh`

### Result 1

* liquidprompt = `fail :(` = not there anymore, it doesn't work
* vte = `pass!` = yes it does work, the current `PWD` is remembered and passed on when spawning new terminal windows and tabs 
* line wrapping = `pass!` = line wrapping works properly for typing long lines until the edge of the window

The conclusion here is that the package `libvte-2.91-common_0.62.3-1ubuntu1_amd64.deb` (as provided by the distro `ubuntu 21.04`) - it does not support the new array functionality for `PROMPT_COMMAND`. So when vte is being sourced after liquidprompt, then it overwrites the previous prompt entirely, and obliterates whatever liquidprompt had done to insert itself into the prompt.

OK... so maybe that needs retesting on the more recent and newer version of `ubuntu 22.04`, and/or that distro needs to improve or update the `vte-2.91.sh` with a newer version that then does include a newer support for bash arrays (where applicable).

### Test 2

Since liquidprompt was being overrided by sourcing the vte.sh, I decided to swap the around order they were being loaded. See what happens, and just switched over positions of these same 2 lines and tried again:

```sh
. /etc/profile.d/vte.sh
. ~/.dev/liquidprompt/liquidprompt
```
### Result 2

* liquidprompt = `pass!` = ansi color prompt, and when I am in a `git` repo, it shows all the git status in the prompt. Excellent!
* vte = `fail :(` = ok so now liquidprompt seems to be overwriting whatever was being previously set by the other `vte.sh`. it is same exact problem, but in reverse 
* line wrapping = `pass!` = line wrapping works properly for typing long lines until the edge of the window

Ah but wait! ...I did not update my version of `liquidprompt` yet! I forgot to do this. So this was with the git commit `24945b9b447976efa6e3ce6682a6d0a2b600c565`

**Conclusion:**  This situation will need me to do a retest with that newest commit you told me about today (the one that you say isn't being merged just yet). --> So that will become **Test 4** (included at the end here, after a different next Test **3** below)....

### Test 3

OK So this is where I must apply some type of a customization / hacks, in order to get both these things working at the same time:

```sh
. /etc/profile.d/vte.sh
. ~/.dev/liquidprompt/liquidprompt
PROMPT_COMMAND+=("__vte_prompt_command")
```

What it does:

1. VTE hook functions are sourced first
2. and VTE also tried to write itself in to `PROMPT_COMMAND=` (but not as an array, as a flat variable, right?)
3. liquidprompt version `24945b9b447976efa6e3ce6682a6d0a2b600c565` loads itself. (this is still an older version and not the new commit you asked me to test).
4. Now I manually add back the VTE, by appending it as a bash array element. So that it does not overwrite the array entry that was previously set by liquidprompt

### Result 3

* liquidprompt = `pass!`
* vte = `pass!` 
* line wrapping = `pass!`

And it all works together. At the same time. Fantastic.


### Test 4

We must now update to the new commit, the one you asked me to test today. See if it makes any help. So we update `liquidprompt` in git, and also we go back to the **Test 1** order, which is VTE, then liquidprompt. If you remember the problem with **Result 1** was that liquidprompt just overwrite the previous VTE prompt with its own. Because it would have to take special extra actions to then preserve it by transferring into a new bash array variable. Which requires some sorts of extra caretaking / janitorial duties.

So we try again. But first we do a `git checkout 3553a658931091813b9e7d` in the liquidprompt source directory.

```sh
. /etc/profile.d/vte.sh
. ~/.dev/liquidprompt/liquidprompt
```

### Result 4

* liquidprompt = `pass!`
* vte = `pass!` = (this was `fail` previously, in the test 2, without the new un-merged commit `3553a65893`)
* line wrapping = `pass!`



# Conclusion

Either **Test 3** or **Test 4** works well enough for me. However with **3** it does require a very small hacking (1 extra line in `~/.profile`). To get it to work. Which is still 1000 miles better than the previous mess (of before).

With your new commit of today it does work still yet even better. However you seem to have some kinds of reservations about merging it? But perhaps you can consider to merge it later on at some point. Perhaps after some extra time? Or after another person can come along, to independently try it out too. But either way, will shall keep on using and testing with your new commit `3553a65893` here on my system. In case any other type of unseen bug.

So sany thanks. It really has made this more reliable situation, for users not to make so many hacks. Because the more individuals have to custom hack is bad, it makes everything more confused. I am no expert on VTE, no expert on liquidprompt, no expert on bash escape sequences. To be able to judge what is correct or what is wrong codes here.

So much gratitude, finally to have a usable shell back again. After all these (2-3) years! It really makes a huge difference for me. All working together. It's genuinely a dream come true. I mean that!

**Comment by Rycieos** [comment] 2022-05-11 19:45
Glad you got it sorted!

Just as a note, we recommend sourcing `liquidprompt` absolutely last (see [the docs](https://liquidprompt.readthedocs.io/en/stable/install.html#shell-installation)) for exactly that reason, that Liquidprompt is smarter than most other things that modify `PROMPT_COMMAND` and will handle weird cases correctly.

On that note, no, I do plan to merge in that commit, probably tomorrow. My earlier reservations were because I did not think I could fix it without breaking other things, but I am pretty confident that this solution that I just found won't break anything.

Just for my curiosity's sake, what does that `/etc/profile.d/vte.sh` actually do? It seems to me `__vte_prompt_command()` just sets the terminal title, and `__vte_osc7()` obviously calls that OSC 7 escape call, but what does that do? Set something in the terminal title? If you are not aware, Liquidprompt has title support as well.

**Comment by dreamcat4** [comment] 2022-05-11 20:31
honestly its some crazy non standard apis. that are just downright bad and not properly standardized.  but as far as i am aware... the primary purpose of OSC 7 is as a mechanism to pass a limited amount of information to some C library called vte. which is a project that came under the maintainership of gnome project. includes the current working directory of the shell. and maybe a couple of other things too. like an icon or something

this vte magic interface can then be called later on. by another process, and those data retrieved via the vte api. so then when you are focused in a terminal window. and you open a new window (or a new tab). then the terminal program calls the vte api and can set the current folder to be the same folder that you were navigated in (from the previous window which you had open when you spwaned the new window).

so idk the magic behind that. but its a very arcane thing.... although i did also ask some people on alacritty tabs issue about vte. if alaceitty uses vte too. and they said there was a different mechanism they used for passing the current directory. which does not need to require or depend upon vte. however that is only for alacritty + tabs (perhaps may be kitty idk). wheras for tiilix and gnome terminal... these one programs do use the VTE interface.

not sure how clear that was. there are probably better explanations elsewhere. with a bit more details

**Comment by Rycieos** [comment] 2022-05-11 23:20
That all makes perfect sense, thanks for the clarification.
