### ISSUE TITLE
tmux session on localhost is misinterpreted as telnet session

### ISSUE THREAD

**Issue by XDex** [nojhan/liquidprompt#377] opened 2015-06-24 14:20 UTC
Hi!
I'm having the same issue as #304 on Debian Testing.
Relevant output:
```
⏚ [andrei@andrei-lt-deb:~] $ echo $(who am i | sed -n 's/.*(\(.*\))/\1/p')
9574).%0
⏚ [andrei@andrei-lt-deb:~] $ tmux -V
tmux 2.0
⏚ [andrei@andrei-lt-deb:~] $ who am i
andrei   pts/1        2015-06-24 17:21 (tmux(9574).%0)
```

**Comment by dolmen** [comment] 2015-07-01 13:43
Do you use the `develop` branch?

**Comment by XDex** [comment] 2015-07-01 21:24
Nope, should I?

**Comment by dolmen** [comment] 2015-07-02 10:04
Yes, you should as it includes many fixes, and some are related to tmux. See [the CHANGES on develop](https://github.com/nojhan/liquidprompt/blob/develop/CHANGES) since the last release.

I'm only considering bug reports against the `develop` branch.

**Comment by dolmen** [comment] 2015-07-02 10:07
Note for example that #370 (which is somewhat related to tmux) has been fixed on the `develop` branch.

**Comment by XDex** [comment] 2015-07-02 10:43
Just switched to develop. The issue persists..

**Comment by XDex** [comment] 2015-07-02 14:04
Fixed in PR #383

**Comment by dolmen** [comment] 2015-07-14 13:30
As I rejected the "fix" in #383, the issue is still open.

**Comment by dolmen** [comment] 2015-07-14 14:43
Closing because duplicate of #304.

**Closed by dolmen** 2015-07-14 14:43 UTC
Labels: bug, duplicate, tmux
