### ISSUE TITLE
Bash builtin `fc` prints `_lp_runtime_before "$_"`

### ISSUE THREAD

**Issue by zyzzyxdonta** [nojhan/liquidprompt#619] opened 2020-09-20 21:21 UTC
Hi,
I found that the bash builtin command `fc` prints `_lp_runtime_before "$_"` before executing the edited command.

Shell: bash 5.0.17(1)-release
Operating system: Linux 5.8.9-200.fc32.x86_64, Fedora release 32 (Thirty Two)
Liquidprompt version: v1.12.0

### Steps to Reproduce
1. Open bash and type `fc`, this will open an editor with your last command in it.
2. Change it to something simple like `echo "Hello"`.
3. Save the file and exit the editor, bash will now execute the command.

### Expected Behavior
```
echo "Hello"
Hello
```

### Current Behavior
```
echo "Hello"
_lp_runtime_before "$_"
Hello
```

### Possible Solution
 I'm not sure whether this is a liquidprompt or a bash bug. I know it doesn't occur e.g. when an autocd is performed where bash also echoes what command it performed.

**Comment by Rycieos** [comment] 2020-09-20 21:33
Yup, I can reproduce this. For sure a weird one.

Obviously more people (including me) need to learn about this cool shell feature if you are the first to report it.

I'll dig in and see if I can find the cause.

**Comment by Rycieos** [comment] 2020-09-21 17:01
I am now sure this is a Bash bug. If anyone can show otherwise or a workaround, I'll be happy to accept a PR or make a fix for it.

I have a vague memory of seeing this issue before, but I can't find a record of it in Liquidprompt issues.

I found [a Bash bug thread](https://www.mail-archive.com/bug-bash@gnu.org/msg24264.html) on this. Relevant snippets:
> **Chet Ramey**:
> fc executes commands from the file after editing. That file can hold an
arbitrary series of commands, so it's useful to have the shell echo the
commands as it reads them. You can't just dump a line at a time, since
there might be compound commands, and dumping the contents of the file
right after editing would be useless. So bash (and ksh93, mksh, zsh, but
not any of the ash descendents) temporarily enable `set -v' while executing
the file.
>
> There's nothing special about those commands, so if the DEBUG trap is
set, the trap handler runs at the right time. There's nothing special
about the DEBUG trap, either, so the verbose setting that's in effect
causes echoing of those commands as they're read.
>
> Hence the discussion topic: should bash disable set -v when executing
the DEBUG trap, should it do that just while running commands from a
file while running `fc', or should it continue with its current behavior?
>
> I'm going to go with a variant of 2: a more general facility that only the
`fc' builtin uses. It will be in the next devel branch push.

And sure enough, in [a commit](https://github.com/bminor/bash/commit/e34adc2c3b6b8722d0316f3b26fe5346faf94dea#diff-c9facb628cbc60ec84479af05c2a567cR7854-R7857) the very next day [Chet fixes it](https://github.com/bminor/bash/commit/e34adc2c3b6b8722d0316f3b26fe5346faf94dea#diff-da22e1d0e8c4775bd273cf5a55ee6e1bR477).

The bash git repo is a mess, but as far as I can tell he never merged that fix into 4.X or 5.0. It was in the first 5.1 alpha. I tested this on bash:5.1-beta, and it did not have this bug. I guess someone should ask Chet Ramey if he can backport the fix?

As for a workaroud; I've only found [one issue](https://stackoverflow.com/q/12363901/8338372) that seems to be the same problem.
And while it claims it found [a prompt that doesn't cause the issue](https://dhampir.no/stuff/bash/bash_prompt), when I tested it I still saw the DEBUG trap echoed to the screen. I don't think there is a workaround.

Unrelated, but I think that prompt has a cool theme going on:
```
,-(user@host)-(0)-(3.52)-(2020-09-21 12:33:32 EDT)
|-(~)
`-$
```
Needs a bit of cleanup, and not exactly my style, but I think such a theme could find a home in Liquidprompt someday.

**Closed by Rycieos** 2020-09-21 17:01 UTC
Labels: bug, runtime

**Comment by zyzzyxdonta** [comment] 2020-09-21 17:54
Wow, thanks for your investigation! If you haven't already, I can send an email his way.

**Comment by Rycieos** [comment] 2020-09-21 17:56
If you could, that would be great.

**Comment by zyzzyxdonta** [comment] 2020-09-21 18:11
Done
