### ISSUE TITLE
loading liquidprompt returns 1?

### ISSUE THREAD

**Issue by aborrero** [nojhan/liquidprompt#395] opened 2015-09-24 07:55 UTC
Hi there!

It seems every time I source liquidprompt I get return code 1 (bash).

The test is rather simple:
```
% source liquidprompt ; echo $?
1
```

The only effect of this behaviour is that everytime a liquidprompt user opens a new prompt, the initial return code is 1, for example:

```
aborrero@deathstar:~ 1 $
```

Do you know why this happens?

**Comment by dolmen** [comment] 2015-09-24 14:39
This is fixed in the develop branch with commit 33c7c0ba777514780ea6dd14676cbd0a2b4094c9.

**Closed by dolmen** 2015-09-24 14:39 UTC

**Comment by dolmen** [comment] 2015-09-24 14:41
Duplicate of #360.
