### ISSUE TITLE
Subversion: externals and uncommited files count as changes

### ISSUE THREAD

**Issue by umrath** [nojhan/liquidprompt#447] opened 2016-06-07 06:25 UTC
Operating system: CentOS 7
Liquid Prompt version (tag, commit): dcc18d2

When changing into directories with Subversion checkouts containing externals each external is counted as a change.
The same applies to files that are not part of the repository.

**Comment by Rycieos** [comment] 2021-01-28 20:26
Sorry for the delay, maybe Subversion has fixed it? I cannot reproduce this:
```
$ svn --version
svn, version 1.10.2 (r1835932)
   compiled Nov  3 2020, 23:13:15 on x86_64-redhat-linux-gnu
...

[mark:/tmp] $ svn co https://svn.apache.org/repos/asf/subversion/trunk subversion && cd subversion
[mark:/tmp/subversion] trunk ‡
[mark:/tmp/subversion] trunk ‡ svn propset svn:externals "external -r1835932 https://svn.apache.org/repos/asf/subversion/trunk" . && svn update
[mark:/tmp/subversion] trunk ‡
[mark:/tmp/subversion] trunk ‡ cd external
[mark:/tmp/subversion/external] trunk ‡  # `external` is highlighted as the repo root now
[mark:/tmp/subversion/external] trunk ‡ cd ..
[mark:/tmp/subversion] trunk ‡  # `subversion` is highlighted as the repo root now, no changes showing
```

**Comment by Rycieos** [comment] 2022-05-10 21:05
Closing as there is not enough information to reproduce this.

If anyone still has this issue, please provide reproduction steps.

**Closed by Rycieos** 2022-05-10 21:05 UTC
Labels: SubVersion, needs information
