### ISSUE TITLE
Set tag for current master

### ISSUE THREAD

**Issue by Gerschtli** [nojhan/liquidprompt#580] opened 2019-08-10 16:17 UTC
Hey,
is it possible to add a tag for the current master HEAD? It seems to be forgotten.

It would help to add liquidprompt to [nixpkgs](https://github.com/NixOS/nixpkgs), the package tree for the distro [NixOS](https://nixos.org). See https://github.com/NixOS/nixpkgs/pull/66429

**Comment by augmentedfourth** [comment] 2019-08-10 16:41
There seems to be interest in this, but the maintainers have mentioned needing some additional process work around creating a new release (particularly around editing the CHANGELOG and making sure open bugs are addressed if possible). See https://github.com/nojhan/liquidprompt/issues/555#issuecomment-416573027 for further information.

**Comment by ottok** [comment] 2020-06-25 18:11
There hasn't been any official releases since 2016: https://github.com/nojhan/liquidprompt/tags

Could you please tag a new version?

NixOS, Homebrew and Debian packagers have hard times providing users with new releases as long as there are no official releases, see e.g. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942483

**Comment by Rycieos** [comment] 2020-06-25 18:17
Working on that right now :)

For anyone who is interested in a new version, please keep an eye out for a `v1.12-rc.1` release in the next few days. Any feedback will help me get the issues worked out faster.

**Comment by Rycieos** [comment] 2020-07-06 02:43
Closing this as duplicate of #526.

Work is progressing, you can follow the progression on the [v1.12 milestone](https://github.com/nojhan/liquidprompt/milestone/1) page.

**Closed by Rycieos** 2020-07-06 02:43 UTC

**Comment by ottok** [comment] 2020-07-22 21:38
Follow-up: the Debian watch now works and a notification about new upstream release is visible at https://tracker.debian.org/pkg/liquidprompt

![image](https://user-images.githubusercontent.com/668724/88231370-cae15f00-cc7c-11ea-8d2c-82194920878d.png)


I also filed a downstream issue urging an update: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966090

**Comment by Rycieos** [comment] 2020-09-07 18:04
@ottok any update on this? Looking at your link it still seems like `1.11-3` is the latest version on the Debian mirrors.

**Comment by ottok** [comment] 2020-09-10 17:24
The latest version has now been uploaded to Debian unstable:
https://tracker.debian.org/pkg/liquidprompt
